/*********Example:1*********/

FROM ubuntu:latest
LABEL maintainer="kba"
RUN apt-get update
CMD ["echo","Hyperledger Fabric Training"]

/****Example:2***********/


FROM node:alpine
LABEL maintainer="kba"
COPY . /app
WORKDIR /app
CMD node app.js



